# Generated by Django 4.2.5 on 2023-09-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remainder_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Complete', 'Complete'), ('Pending', 'Pending')], default='Pending', max_length=12)),
            ],
            options={
                'db_table': 'Note',
            },
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
